name: Sync Data from Other Firebase

on:
  schedule:
    - cron: '0 10 * * *'   # বাংলাদেশ সময় বিকাল ৪টায় চালাবে
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5   # ✅ v4 থেকে v5 এ আপডেট
        # with:
        #   node-version: '24'      # 🔴 এই লাইনটি সরিয়ে ফেলুন

      - name: Setup Node.js
        uses: actions/setup-node@v5   # ✅ v4 থেকে v5 এ আপডেট
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm install firebase-admin

      - name: Run sync script
        env:
          SOURCE_FIREBASE_SA: ${{ secrets.SOURCE_FIREBASE_SA }}
        run: node scripts/sync-data.js
